### ISSUE TITLE
Possibly document what `loaders: graphQLBookshelf.getLoaders()` is?

### ISSUE THREAD

**Issue by hailwood** [weyoss/graphql-bookshelfjs#3]
In the readme where we have
```javascript
graphql( 
    schema, 
    query, 
    null, 
    { 
        loaders: graphQLBookshelf.getLoaders() // include loaders for performing batch queries
    }
)
```

It just took me quite some googling/source code reading to find that the fourth parameter of the reference graphql implementation is the contextArg which meant for me and anyone else using an apollo server implementation (thousands of installs per week) the [GraphQLOptions](http://dev.apollodata.com/tools/graphql-server/setup.html#graphqlOptions) object looks like this.

```javascript
{
    schema: graphQLSchema,
    context: {
        loaders: graphQLBookshelf.getLoaders()
    }
},
````

I'd update it myself and submit a pull request but I'm not sure how you would like to proceed; 
Perhaps just updating the comment to read 
```javascript
// include loaders in the context object for performing batch queries
```
just a suggestion to help people using this great package :)

**Comment by weyoss** [comment]
I understand what you mean. But unfortunately documenting graphql API is out of scope of this library. Please check out the API docs for graphql-js package at [http://graphql.org/graphql-js/graphql/#graphql](http://graphql.org/graphql-js/graphql/#graphql). Before using this library, I highly recommend to get familiar first with graphql-js and have a good understanding of it. The same about bookshelf :) Anyway, regarding the comment, I will try to make it more clear, considering your suggestion, in the next release! Thank you.

**Comment by weyoss** [comment]
Closing as resolved.
